version: 0.1
log:
  level: info
  fields:
    environment: test
reporting:
  bugsnag:
    apiKey: "99153094f8fbc48d175b9097f329ded6"
http:
  addr: localhost:8034
  secret: "(b7JmIC9!d++U?H8Yf^:[JF=+L|wtxIzHnZ4i_U.9N$iIp|Zm0"
mongodb:
  uri: mongodb://localhost:27017
  name: thatiq-db
redis:
  addr: localhost:6379
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
