version: '3'

services:
  db:
    image: mongo:3.6.8-stretch
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
  redis:
    image: redis:4.0.11-alpine
    ports:
      - "6379:6379"
  thatique:
    build: .
    volumes:
      - ./docker/data:/data
    ports:
      - "8000:8034"
    depends_on:
      - db
      - redis
volumes:
  mongodata:
