swagger: '2.0'
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
info:
  version: 0.1.0
  title: Thatiq
  description: description
  termsOfService: terms
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
definitions:
  error_response:
    type: object
    properties:
      message:
        type: string
        description: the error message
  user:
    type: object
    properties:
      id:
        type: string
        description: The unique id of user
      status:
        type: string
        description: user status, either active, inactive or locked
      created_at:
        type: string
        format: date-time
      profile:
        type: object
        properties:
          name:
            type: string
            description: The name of user
          picture:
            type: string
            description: Public URL of user's profile
          bio:
            type: string
            description: 'biography of user, this field maybe empty'
          web:
            type: string
            description: User's web URL
paths:
  /users:
    get:
      summary: List users
      description: |
        Return a list of users
      operationId: UserLists
      responses:
        '200':
          description: "no errors"
          schema:
            type: object
            properties:
              users:
                type: array
                items:
                  $ref: '#/definitions/user'
        '500':
          description: "internal server errors"
          schema:
            $ref: '#/definitions/error_response'